name: Build Release - Windows

permissions:
  contents: write
  statuses: write
  checks: write

on:
  workflow_call:
    secrets:
      SIGNALING_URL:
        required: true
      GH_TOKEN:
        required: true

env:
  SIGNALING_URL: ${{ secrets.SIGNALING_URL }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: get-npm-version
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3.2
        with:
          path: .

      - name: Write .env
        run: echo SIGNALING_URL=${{ secrets.SIGNALING_URL }} > .erb/.env

      - name: Build Frontend
        run: npm run build

      - name: Publish Electron
        run: npm run app:dist

      - name: Show DIR
        run: ls release/build

      - name: Upload Binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: release/build/*.{exe,yml}
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true


